// Code generated by rscli. DO NOT EDIT.

package telegram

import (
	"github.com/Red-Sock/go_tg"

	"github.com/Red-Sock/Red-Cart/internal/config"
)

func New(cfg *config.Config) *go_tg.Bot {
	return go_tg.NewBot(cfg.GetString(config.ServerTelegramAPIKey))
}
