app_info:
    name: Red-Sock/Red-Cart
    version: v0.0.4
    startup_duration: 10s
data_sources:
    - resource_name: postgres
      host: localhost
      port: 5432
      user: red_cart
      pwd: ""
      name: red_cart
      ssl_mode: ""
    - resource_name: telegram
      api_key: telegram_bot_token
server: []
environment: []
