app_info:
    name: github.com/Red-Sock/Red-Cart
    version: v0.0.1
    startup_duration: 10s
server:
    telegram:
        api_key: ""
data_sources:
    postgres:
        host: localhost
        port: 5432
        name: "red_cart"
        user: "red_cart"
        pwd: ""
