app_info:
    name: github.com/Red-Sock/Red-Cart
    version: v0.0.15
    startup_duration: 10s
server: []
data_sources:
    - resource_name: postgres
      host: postgres
      port: 5432
      name: "red_cart"
      user: "red_cart"
      pwd: ""
    - resource_name: telegram
      api_key: