name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - RC-*

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: RedSockActions/create_pr@v0.0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.6
        env:
          POSTGRES_DB: red_cart
          POSTGRES_USER: red_cart
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    needs:
      - create-pr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test ./...